export interface CreateProjectRequest {
     id: string,
    nome: string,
    cnpj: string,
    email: string,
    razaoSocial: string,
    endereco: string,
    quantidadeDeProjetos: string,
    quantidadeDePessoas: string,
    ativo: string,
    dataAbertura: string,
    dataFechamento: string,
    dataPrevista: string,
    status: string,
}